"""Pytest fixtures for the fake-CLI adapter integration harness.

The :func:`fake_cli_fixture` fixture creates a tempdir of shell wrappers
named ``claude``, ``codex``, ``gemini``, ``aider``, ``ollama`` (etc.),
each of which forwards to ``fake_cli.py`` with a profile-specific env
var set.  Tests use the fixture to:

1. Prepend the wrappers directory onto ``PATH`` so the adapter's
   ``subprocess.Popen([cli, ...])`` resolves to the fake binary.
2. Configure the fake's behaviour for the test (success / error /
   stream-then-die / hang / no_output) via a config file the fake reads
   on every invocation.
3. Recover the actual argv and env that the spawned process saw, by
   pointing the fake at JSON dump files.

Wrappers are POSIX shell scripts.  Windows is unsupported (fcntl,
symlinks, and ``#!/usr/bin/env sh`` shebangs all behave differently);
tests using this fixture skip on ``platform.system() == "Windows"``.
"""

from __future__ import annotations

import json
import os
import platform
import stat
from collections.abc import Generator
from dataclasses import dataclass, field
from pathlib import Path

import pytest

# Source path for the fake-CLI script; resolved once per process so the
# fixture stays cheap when many tests request it.
_FAKE_CLI_PATH: Path = (Path(__file__).resolve().parent / "fake_cli.py").resolve()

# Profiles the harness ships with.  Each entry is (profile, [bin names]).
# A profile may install multiple wrapper binaries when the upstream CLI's
# argv[0] name differs from the bernstein-side adapter slug — e.g.
# Cursor's binary is ``cursor-agent`` but the bernstein registry slug is
# ``cursor``. The fake_cli auto-detects the profile from argv[0]
# basename via :data:`fake_cli._BINARY_TO_PROFILE`.
_PROFILE_BINARIES: tuple[tuple[str, tuple[str, ...]], ...] = (
    # Top-5 (original)
    ("claude", ("claude",)),
    ("codex", ("codex",)),
    ("gemini", ("gemini",)),
    ("aider", ("aider",)),
    ("ollama", ("ollama",)),
    # Top-6 through top-10 (this PR)
    ("cursor", ("cursor-agent", "cursor")),
    ("q_dev", ("q", "q_dev")),
    ("junie", ("junie",)),
    ("devin_terminal", ("devin", "devin_terminal")),
    ("mistral", ("vibe", "mistral")),
)

# Backwards-compatible flat tuple of profile names — older tests reference
# this directly.
SUPPORTED_PROFILES: tuple[str, ...] = tuple(profile for profile, _ in _PROFILE_BINARIES)

# Wrapper shell template.  ${PROFILE} is replaced at write-time; the
# config-file path is read at run-time so a single fixture can rewrite
# the config between adapter spawns within one test.
_WRAPPER_TEMPLATE: str = """#!/bin/sh
# Auto-generated by tests.integration.fake_cli.conftest_adapters
export BERNSTEIN_FAKE_CLI_PROFILE="${PROFILE}"
CONFIG_FILE="${CONFIG_FILE_PATH}"
if [ -f "$CONFIG_FILE" ]; then
    # Source key=value lines (mode, exit code, dump paths).  The config
    # writer escapes values, so a single ``.`` is safe here.
    . "$CONFIG_FILE"
fi
exec "${PYTHON_BIN}" "${FAKE_CLI_PATH}" "$@"
"""


@dataclass
class FakeCLIHandle:
    """Handle returned by :func:`fake_cli_fixture` for in-test control.

    Attributes:
        bin_dir: Directory of wrapper scripts to prepend onto ``PATH``.
        config_path: Path to the shared config file.  Tests rewrite this
            between adapter spawns to change behaviour mid-fixture.
        argv_dump: Path the fake will dump argv into per spawn.
        env_dump: Path the fake will dump env into per spawn.
    """

    bin_dir: Path
    config_path: Path
    argv_dump: Path
    env_dump: Path
    _writes: list[dict[str, str]] = field(default_factory=list)

    def configure(
        self,
        *,
        mode: str = "success",
        exit_code: int = 0,
        delay_s: float = 0.0,
        stdout: str | None = None,
        stderr: str | None = None,
    ) -> None:
        """Rewrite the shared config file with the given behaviour.

        Args:
            mode: One of ``success`` / ``error`` / ``stream_then_die``
                / ``hang`` / ``no_output``.
            exit_code: Override exit code in error/stream_then_die modes.
            delay_s: Sleep N seconds during success mode (for streaming
                tests).
            stdout: Verbatim stdout to emit; replaces profile default.
            stderr: Verbatim stderr to emit; replaces default error msg.
        """
        lines: list[str] = [
            f"export BERNSTEIN_FAKE_CLI_MODE={_shell_quote(mode)}",
            f"export BERNSTEIN_FAKE_CLI_EXIT_CODE={int(exit_code)}",
            f"export BERNSTEIN_FAKE_CLI_DELAY_S={float(delay_s)}",
            f"export BERNSTEIN_FAKE_CLI_ARGV_DUMP={_shell_quote(str(self.argv_dump))}",
            f"export BERNSTEIN_FAKE_CLI_ENV_DUMP={_shell_quote(str(self.env_dump))}",
        ]
        if stdout is not None:
            lines.append(f"export BERNSTEIN_FAKE_CLI_STDOUT={_shell_quote(stdout)}")
        if stderr is not None:
            lines.append(f"export BERNSTEIN_FAKE_CLI_STDERR={_shell_quote(stderr)}")
        self.config_path.write_text("\n".join(lines) + "\n", encoding="utf-8")
        self._writes.append({"mode": mode, "exit_code": str(exit_code)})

    def read_argv(self) -> list[str]:
        """Return the argv recorded by the most recent fake-CLI invocation.

        Returns ``[]`` when the fake hasn't run yet — handy for tests
        that want to confirm a spawn happened at all.
        """
        if not self.argv_dump.exists():
            return []
        try:
            data = json.loads(self.argv_dump.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return []
        return list(data) if isinstance(data, list) else []

    def read_env(self) -> dict[str, str]:
        """Return the env recorded by the most recent fake-CLI invocation."""
        if not self.env_dump.exists():
            return {}
        try:
            data = json.loads(self.env_dump.read_text(encoding="utf-8"))
        except (OSError, json.JSONDecodeError):
            return {}
        return dict(data) if isinstance(data, dict) else {}


def _shell_quote(value: str) -> str:
    """Single-quote ``value`` for a POSIX shell ``export`` line."""
    # Replace any single quotes inside the value with the standard
    # ``'\''`` escape; wrap the whole thing in single quotes.
    return "'" + value.replace("'", "'\\''") + "'"


def _write_wrapper(
    bin_dir: Path,
    binary_name: str,
    *,
    config_path: Path,
    profile: str | None = None,
) -> Path:
    """Write a profile-specific wrapper script and mark it executable.

    Args:
        bin_dir: Directory the wrapper is created under.
        binary_name: Wrapper file name (typically the upstream CLI's
            argv[0] basename — ``cursor-agent``, ``vibe``, etc.).
        config_path: Path to the shared per-fixture config file.
        profile: Profile slug to bake into the wrapper. Defaults to
            ``binary_name`` so callers passing the profile slug directly
            keep working without code changes.

    Returns:
        Path to the newly written wrapper.
    """
    import sys

    effective_profile = profile if profile is not None else binary_name
    wrapper = bin_dir / binary_name
    body = (
        _WRAPPER_TEMPLATE.replace("${PROFILE}", effective_profile)
        .replace("${CONFIG_FILE_PATH}", str(config_path))
        .replace("${FAKE_CLI_PATH}", str(_FAKE_CLI_PATH))
        .replace("${PYTHON_BIN}", sys.executable)
    )
    wrapper.write_text(body, encoding="utf-8")
    # Owner-rwx + group/other rx is plenty for a test fixture on POSIX.
    wrapper.chmod(stat.S_IRWXU | stat.S_IRGRP | stat.S_IXGRP | stat.S_IROTH | stat.S_IXOTH)
    return wrapper


@pytest.fixture
def fake_cli_fixture(
    tmp_path: Path,
    monkeypatch: pytest.MonkeyPatch,
) -> Generator[FakeCLIHandle, None, None]:
    """Provide a :class:`FakeCLIHandle` and prepend its bin dir onto PATH.

    The fixture creates one wrapper per :data:`SUPPORTED_PROFILES` entry
    in a per-test ``tmp_path / "fake_bin"`` directory, writes a default
    success-mode config file, and prepends the directory onto ``PATH``
    via ``monkeypatch`` (auto-restored on teardown).

    Tests change the fake's behaviour via :meth:`FakeCLIHandle.configure`
    and recover argv/env via :meth:`FakeCLIHandle.read_argv` / ``read_env``.
    """
    if platform.system() == "Windows":
        pytest.skip("fake-CLI harness uses POSIX shell wrappers")

    bin_dir = tmp_path / "fake_bin"
    bin_dir.mkdir()
    config_path = tmp_path / "fake_cli.config.sh"
    argv_dump = tmp_path / "fake_cli.argv.json"
    env_dump = tmp_path / "fake_cli.env.json"

    handle = FakeCLIHandle(
        bin_dir=bin_dir,
        config_path=config_path,
        argv_dump=argv_dump,
        env_dump=env_dump,
    )
    handle.configure(mode="success")

    # Install one wrapper per (profile, binary) pair. Every supported
    # profile gets at least one wrapper named after the profile slug
    # itself; profiles whose upstream CLI binary differs (cursor-agent,
    # vibe, etc.) get an additional wrapper under that physical name so
    # ``Popen([upstream_binary, ...])`` resolves on PATH without any
    # shim on the bernstein side.
    for profile, binaries in _PROFILE_BINARIES:
        for binary in binaries:
            _write_wrapper(bin_dir, binary, config_path=config_path, profile=profile)

    # Prepend the fake-bin dir onto PATH so adapter Popen calls resolve
    # the wrappers instead of any real CLI on the host.
    existing_path = os.environ.get("PATH", "")
    monkeypatch.setenv("PATH", f"{bin_dir}{os.pathsep}{existing_path}")

    yield handle
